### ISSUE TITLE
A Linux compile tutorial would be appriciated

### ISSUE THREAD

**Issue by rea987** [soulweaver91/project-carrot-pcae#6]

**Comment by soulweaver91** [comment]
This should indeed be added. Unlike with the other repos, I didn't yet really get around to rewrite this one to not be so terrible as it is (related: #2), so I don't yet have the qmake related files in here either. I'll look into this whenever I have time, possibly starting with just generating those files and ignoring the rewrite task for now.

**Comment by soulweaver91** [comment]
Hmm, it appears this will need a bit more work than just adding the project files after all. Using those, the code doesn't compile on Linux currently - GCC throws a compilation error while Clang outright crashes (!), maybe for the same reason, maybe not.

**Edit:**
The `qmake` branch can now be compiled on Linux; works normally with GCC, but with Clang the relevant Makefile has to be edited; with the default optimization level in `CXXFLAGS` it crashes but with `O0` it doesn't. Didn't test if it actually does what it's supposed to, though.

**Comment by rea987** [comment]
As it seems, both **Project Carrot**, **Project Carrot Tileset Converter** and **Project Carrot Level Converter** received compiling tutorial for GNU/Linux. Is there any progress for **Project Carrot Anim Extractor**?

Thanks, regards.

**Comment by soulweaver91** [comment]
Sorry, while juggling between work and two university assignments I haven't had that much time to deal with my personal projects recently 😩 

As I mentioned in the above comment, you can checkout the `qmake` branch and follow mostly the same steps with PCTC/PCLC, that is, `qmake -spec linux-clang`, replace the optimization level (`O1`, `O2` or `O3` probably) in `CXXFLAGS` with `O0` in the `Makefile`, then `make release` for now. Or `qmake -spec linux-g++ && make release` should work as well, I guess. I didn't push that yet to master due to that yet unsolved Clang crash issue, but I'll try to get to it eventually 🙂

**Comment by rea987** [comment]
Sweet, thanks!
